Workshop list filtering
societree/app-next pull request #52
Opened 2022-12-17 14:19 UTC by mika018

* Implemented text search, category and time filters. 
* Manually tested everything and happy that it works but we should definitely add some unit tests.
* There is a question of whether we want to include a filter on locaton (virtual or not)? I propose we leave that for now as we have no idea what would be the ratio of virtual/physical and it will be easy to add at a later stage. thoughts @harryndavies ?
* We don't have a loading animation but I raised a separate issue to track that. See #51

Closes #13

2022-12-24 16:25 UTC, harryndavies requested changes
Nice work on this, I’ve left a few comments 👍

2023-01-06 12:58 UTC, mika018 commented on components/Workshop/WorkshopList.tsx
> +  const filterWorkshops = useCallback(async (searchParams: any) => {
Done

2023-01-06 12:58 UTC, mika018 commented on components/Workshop/WorkshopList.tsx
> +  }, [search]);
Added

2023-01-06 12:58 UTC, mika018 commented on utils/dates.ts
> +  var today = new Date();
Ah makes sense, changed them all :+1:

2023-01-06 12:58 UTC, mika018 commented on components/Workshop/WorkshopListFilter.tsx
> +          {config.timeFilters.map((c) => (
Yes, I updated both time filters and categories

2023-01-06 12:59 UTC, mika018 commented on app-config.ts
> +  timeFilters: Object.values(TimeFilter)
Makes sense, I ended up just calling it directly in the component as that is the only place we use it

2023-01-06 13:01 UTC, mika018 commented on components/Workshop/WorkshopListFilter.tsx
>    onFilterChange(filter: any): void;
I have failed to make this work. The `watch` method ends up complaining as it leaves space for the filter values to be `undefined` even though I am setting the default values to be actual values (empty strings). I am gonna look at it again after lunch. This should be the final blocker of this PR

2023-05-30 17:50 UTC, merged